on: [workflow_dispatch]
jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v3
      - run: echo All Good
      - run: cat /etc/os-release
      - run: pwd
      - run: ls -l /
      - run: ls -l /workspace/
      - run: which find
      - run: ls -l /workspace/aygath/
      - run: ls -l /workspace/aygath/zon/
      - run: find /workspace/aygath/zon/
      - run: ./configure
      - run: make