on: [workflow_dispatch]
jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - run: echo All Good
      - run: cat /etc/os-release
      - run: which automake
      - run: which autoconf
      - run: pwd
      - run: ls -al 
      - run: find .