on: [workflow_dispatch]
jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - run: echo All Good
      - run: cat /etc/os-release
      - run: pwd
      - run: ls -l /
      - run: ls -l /workspace/aygath/zon/*
      - run: which find
      - run: find /workspace/aygath/zon/