on: [workflow_dispatch]
jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - run: echo All Good
      - run: cat /etc/os-release
      - run: pwd
      - run: ls ${PWD}
      - run: find ${PWD} 